name: Django CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Run Jobs
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: 'a secret-key for everybody'
      DJANGO_ADMIN_URL: 'test-admin-url'
      EMAIL_BACKEND: 'django.core.mail.backends.console.EmailBackend'
      ALLOWED_HOSTS: "*"

    steps:
      - name: Get The Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements.dev.txt

      - name: Install OS packages
        run: |
          # Graphviz support
          # python3-dev graphviz libgraphviz-dev
          sudo apt install python3-dev graphviz libgraphviz-dev

      - name: Test It
        run: make coverage

#      - name: Check deploy configuration
#        run: ./manage.py check --deploy --fail-level WARNING
#        env:
#          DATABASE_URL: 'sqlite://:memory:'
#          SECRET_KEY: 'zt(6jlr#oquxm2t%ryh#n+-72p^(3kn-bf&q$5x16#o%1im-s7!'
#          SECURE_SSL_REDIRECT: 'on'

